// hash-users.mjs
import bcrypt from 'bcrypt';

const rawUsers = [
    ['j.murphy93', 'Sunflower!92'],
    ['katrina.lee', 'BlueOcean2021'],
    ['aj_singh', 'MangoJuice_88'],
    ['emily.chan87', 'CoffeeLover#7'],
    ['nathan.b_', 'SecureMe$456'],
    ['marcus.taylor', 'WinterFox!23'],
    ['sasha_kim', 'Lemonade99'],
    ['devon.ramirez', 'GuitarHero#4'],
    ['amy.wong', 'BubbleTea2022'],
    ['liam.evans', 'DinoTime!55'],
    ['hannah.moore', 'GoPackers2021'],
    ['b_ortega', 'TravelBug#33'],
    ['isabelle.j', 'StrongPass8*'],
    ['tyrone_w', 'CherryTree@7'],
    ['chloe.nguyen', 'SoccerStar44'],
    ['erik.jensen', 'Sk8board2023'],
    ['laura_park', 'BalletShoes88'],
    ['mike.davis88', 'GrilledCheese9'],
    ['noah_scott', 'NightOwl@12'],
    ['amber.j_', 'OceanWave*1'],
    ['victor_l', 'PlantParent_5'],
    ['diana.h', 'DogMom2020'],
    ['trent.p', 'PixelPunch$3'],
    ['serena.cho', 'KDrama4Life'],
    ['ryan.woods', 'MapleLeaf_99'],
    ['julie_chen', 'SunsetDrive7'],
    ['felix.kim', 'GamerZone!7'],
    ['tina.morris', 'YogaVibes21'],
    ['blake_m', 'CryptoKing2022'],
    ['sophia.r', 'BobaAddict88'],
    ['henry_cole', 'CheeseCake3@'],
    ['jamie_s', 'SleepyTiger!1'],
    ['megan_hunt', 'RoadTrip2021'],
    ['leo.grant', 'Fireworks#44'],
    ['danielle.m', 'SkiTrip!10'],
    ['trevor.y', 'BassDrop_32'],
    ['kayla_b', 'RainyDays99'],
    ['cody.m', 'QuietLake2020'],
    ['andrea.ross', 'Moonwalker88'],
    ['zach_h', 'CodingNinja7*'],
    ['camila.f', 'SpaDay@5'],
    ['ethan_b', 'RetroVibes23'],
    ['ava.j', 'HappyFeet_4'],
    ['julian.k', 'MarvelFan21!'],
    ['grace_choi', 'StarDust33'],
    ['owen.tan', 'PopcornTime@2'],
    ['nina_s', 'GardenGnome1'],
    ['jared.l', 'SkaterDude55'],
    ['lily.a', 'BeachVibes_7'],
    ['harper.m', 'PianoKeys8*'],
    ['lucas.d', 'DragonQuest99'],
    ['zoe_h', 'SpaceNerd22'],
    ['colton.g', 'RockClimb88'],
    ['melanie_r', 'PastaQueen@1'],
    ['aiden.c', 'SwiftFan_13'],
    ['kelsey.v', 'FreshBrew@9'],
    ['brian_xu', 'ChessChamp7'],
    ['rebecca.t', 'TheatreKid44'],
    ['eli.p', 'FastTrack#6'],
    ['madison.f', 'GlitterBomb3'],
    ['hunter.k', 'BurgerBoss9'],
    ['vanessa.c', 'IceCream88'],
    ['josh.y', 'NeonLights1'],
    ['carla_m', 'QuokkaSmile7'],
    ['adrian.n', 'LunarTide33'],
    ['brittany.g', 'JetLagged2'],
    ['dylan_ho', 'PuzzleSolver_4'],
    ['alina_v', 'GalaxyWalk3'],
    ['kevin_park', 'JungleRun21'],
    ['stella_m', 'TeaTime_88'],
    ['mason.l', 'FlashDrive!2'],
    ['natalie.r', 'Spaghetti9*'],
    ['brandon.j', 'GoldenEagle_1'],
    ['julia_fox', 'PastelDream5'],
    ['connor.b', 'OrbitRush3'],
    ['amelia.k', 'IceQueen@4'],
    ['sean.t', 'StormRider99'],
    ['iris.h', 'Polaroid88'],
    ['caleb.n', 'SilentHill3'],
    ['paige_y', 'SapphireSky1'],
    ['elijah.m', 'DesertBloom_2'],
    ['carmen.r', 'MintyFresh7'],
    ['gabe_z', 'ThunderCat_8'],
    ['tiffany.x', 'CaffeineFix@5'],
    ['reece.k', 'Snowflake_22'],
    ['bianca.d', 'CoralReef4'],
    ['landon_w', 'DoodleKing9'],
    ['faith.j', 'GoldenHour@6'],
    ['carter_s', 'CodeCrush88'],
    ['daisy_t', 'GreenTea*11'],
    ['isaac.f', 'MusicWave7'],
    ['elena.m', 'PinkTulips33'],
    ['chris.o', 'VaporTrail1'],
    ['heidi_b', 'ChocoMint7'],
    ['tristan.m', 'FireFly@88'],
    ['leila.c', 'SundaeFun4'],
    ['miles.j', 'BlizzardRush6'],
    ['cynthia_v', 'NotebookDoodle'],
    ['ray_k', 'PantherMode#2'],
    ['sydney.h', 'LavenderSky8']  
];

const users = new Map();

for (const [username, password] of rawUsers) {
  const hash = await bcrypt.hash(password, 10);
  users.set(username, hash);
}

// Output to console or file
console.log("const users = new Map([");
for (const [username, hash] of users) {
  console.log(`  ['${username}', '${hash}'],`);
}
console.log("]);");