import inquirer from "inquirer";

const drivingAges = new Map([
  ["Afghanistan", 18],
  ["Albania", 18],
  ["Algeria", 18],
  ["Andorra", 18],
  ["Angola", 18],
  ["Antigua and Barbuda", 18],
  ["Argentina", 17],
  ["Armenia", 18],
  ["Australia", 16], // Varies by state; 16–18
  ["Austria", 17],
  ["Azerbaijan", 18],
  ["Bahamas", 17],
  ["Bahrain", 18],
  ["Bangladesh", 18],
  ["Barbados", 18],
  ["Belarus", 18],
  ["Belgium", 18],
  ["Belize", 18],
  ["Benin", 18],
  ["Bhutan", 18],
  ["Bolivia", 18],
  ["Bosnia and Herzegovina", 18],
  ["Botswana", 18],
  ["Brazil", 18],
  ["Brunei", 18],
  ["Bulgaria", 18],
  ["Burkina Faso", 18],
  ["Burundi", 18],
  ["Cambodia", 18],
  ["Cameroon", 16],
  ["Canada", 16], // Varies by province; 14–16
  ["Cape Verde", 18],
  ["Central African Republic", 18],
  ["Chad", 18],
  ["Chile", 18],
  ["China", 18],
  ["Colombia", 16],
  ["Comoros", 18],
  ["Congo (Brazzaville)", 18],
  ["Congo (Kinshasa)", 18],
  ["Costa Rica", 18],
  ["Croatia", 18],
  ["Cuba", 18],
  ["Cyprus", 18],
  ["Czech Republic", 18],
  ["Denmark", 18],
  ["Djibouti", 18],
  ["Dominica", 18],
  ["Dominican Republic", 16],
  ["Ecuador", 18],
  ["Egypt", 18],
  ["El Salvador", 15],
  ["Equatorial Guinea", 18],
  ["Eritrea", 18],
  ["Estonia", 18],
  ["Eswatini", 18],
  ["Ethiopia", 18],
  ["Fiji", 17],
  ["Finland", 18],
  ["France", 18],
  ["Gabon", 18],
  ["Gambia", 18],
  ["Georgia", 17],
  ["Germany", 18],
  ["Ghana", 18],
  ["Greece", 18],
  ["Grenada", 18],
  ["Guatemala", 18],
  ["Guinea", 18],
  ["Guinea-Bissau", 18],
  ["Guyana", 17],
  ["Haiti", 18],
  ["Honduras", 18],
  ["Hungary", 17],
  ["Iceland", 17],
  ["India", 18],
  ["Indonesia", 17],
  ["Iran", 18],
  ["Iraq", 18],
  ["Ireland", 17],
  ["Israel", 17],
  ["Italy", 18],
  ["Jamaica", 18],
  ["Japan", 18],
  ["Jordan", 18],
  ["Kazakhstan", 18],
  ["Kenya", 18],
  ["Kiribati", 18],
  ["Korea, North", 18],
  ["Korea, South", 18],
  ["Kuwait", 18],
  ["Kyrgyzstan", 18],
  ["Laos", 18],
  ["Latvia", 18],
  ["Lebanon", 18],
  ["Lesotho", 18],
  ["Liberia", 18],
  ["Libya", 18],
  ["Liechtenstein", 18],
  ["Lithuania", 18],
  ["Luxembourg", 18],
  ["Madagascar", 18],
  ["Malawi", 18],
  ["Malaysia", 17],
  ["Maldives", 18],
  ["Mali", 18],
  ["Malta", 18],
  ["Marshall Islands", 18],
  ["Mauritania", 18],
  ["Mauritius", 18],
  ["Mexico", 18],
  ["Micronesia", 18],
  ["Moldova", 18],
  ["Monaco", 18],
  ["Mongolia", 18],
  ["Montenegro", 18],
  ["Morocco", 18],
  ["Mozambique", 18],
  ["Myanmar", 18],
  ["Namibia", 18],
  ["Nauru", 18],
  ["Nepal", 18],
  ["Netherlands", 18],
  ["New Zealand", 17.5],
  ["Nicaragua", 18],
  ["Niger", 23],
  ["Nigeria", 18],
  ["North Macedonia", 18],
  ["Norway", 18],
  ["Oman", 18],
  ["Pakistan", 18],
  ["Palau", 18],
  ["Panama", 18],
  ["Papua New Guinea", 18],
  ["Paraguay", 18],
  ["Peru", 18],
  ["Philippines", 17],
  ["Poland", 18],
  ["Portugal", 18],
  ["Qatar", 18],
  ["Romania", 18],
  ["Russia", 18],
  ["Rwanda", 18],
  ["Saint Kitts and Nevis", 18],
  ["Saint Lucia", 18],
  ["Saint Vincent and the Grenadines", 18],
  ["Samoa", 18],
  ["San Marino", 18],
  ["Sao Tome and Principe", 18],
  ["Saudi Arabia", 16],
  ["Senegal", 18],
  ["Serbia", 18],
  ["Seychelles", 18],
  ["Sierra Leone", 18],
  ["Singapore", 18],
  ["Slovakia", 18],
  ["Slovenia", 18],
  ["Solomon Islands", 18],
  ["Somalia", 18],
  ["South Africa", 18],
  ["South Sudan", 18],
  ["Spain", 18],
  ["Sri Lanka", 17],
  ["Sudan", 18],
  ["Suriname", 18],
  ["Sweden", 18],
  ["Switzerland", 18],
  ["Syria", 18],
  ["Taiwan", 18],
  ["Tajikistan", 18],
  ["Tanzania", 18],
  ["Thailand", 18],
  ["Timor-Leste", 18],
  ["Togo", 18],
  ["Tonga", 18],
  ["Trinidad and Tobago", 17],
  ["Tunisia", 18],
  ["Turkey", 18],
  ["Turkmenistan", 18],
  ["Tuvalu", 18],
  ["Uganda", 18],
  ["Ukraine", 18],
  ["United Arab Emirates", 18],
  ["United Kingdom", 17],
  ["United States", 16], // Varies by state; 14–16
  ["Uruguay", 18],
  ["Uzbekistan", 18],
  ["Vanuatu", 18],
  ["Vatican City", 18],
  ["Venezuela", 18],
  ["Vietnam", 18],
  ["Yemen", 18],
  ["Zambia", 16],
  ["Zimbabwe", 16]
]);

async function getDrivingAge() {
  const age = await inquirer.prompt([
    {
      type: "number",
      name: "age",
      message: "What is your age?",
      validate: (value) => {
        if ((value) <= 0) {
          return "Please enter a valid number";
        }
        return true;
      },
    },
  ]);
  return age.age;
}

let age = await getDrivingAge()
for (let [country, drivingAge] of drivingAges) {
  if (age >= drivingAge) {
    console.log(`You can drive in ${country}`);
  }
}